const SET_MARKET_CATEGORY_VALUE = 'SET CATEGORY VALUE';
const SET_MARKET_NAME_VALUE = 'SET MARKET NAME VALUE';

const GET_MARKETS_BY_NAME = 'GET MARKETS BY NAME';
const GET_MARKETS_BY_NAME_START = 'GET MARKETS BY NAME START';
const GET_MARKETS_BY_NAME_SUCCESS = 'GET MARKETS BY NAME SUCCESS';
const GET_MARKETS_BY_NAME_FAIL = 'GET MARKETS BY NAME FAIL';

const GET_MARKETS_BY_NAME_AND_LOCATION = 'GET MARKETS BY NAME AND LOCATION';
const GET_MARKETS_BY_NAME_AND_LOCATION_START = 'GET MARKETS BY NAME AND LOCATION START';
const GET_MARKETS_BY_NAME_AND_LOCATION_SUCCESS = 'GET MARKETS BY NAME AND LOCATION SUCCESS';
const GET_MARKETS_BY_NAME_AND_LOCATION_FAIL = 'GET MARKETS BY NAME AND LOCATION FAIL';

const GET_MARKETS_BY_CATEGORY = 'GET MARKETS BY CATEGORY';
const GET_MARKETS_BY_CATEGORY_START = 'GET MARKETS BY CATEGORY_START';
const GET_MARKETS_BY_CATEGORY_SUCCESS = 'GET MARKETS BY CATEGORY_SUCCESS';
const GET_MARKETS_BY_CATEGORY_FAIL = 'GET MARKETS BY CATEGORY FAIL';
const GET_MARKETS_BY_CATEGORY_AND_LOCATION = 'GET MARKETS BY CATEGORY AND LOCATION';
const GET_MARKETS_BY_CATEGORY_AND_LOCATION_START = 'GET MARKETS BY CATEGORY AND LOCATION START';
const GET_MARKETS_BY_CATEGORY_AND_LOCATION_SUCCESS = 'GET MARKETS BY CATEGORY AND LOCATION SUCCESS';
const GET_MARKETS_BY_CATEGORY_AND_LOCATION_FAIL= 'GET MARKETS BY CATEGORY AND LOCATION FAIL';
const RESET_MARKETS = 'RESET MARKETS';

const SET_LOCATION = 'SET LOCATION';
const SET_DISPLAY_LOCATION = 'SET DISPLAY LOCATION';


export {
    SET_MARKET_CATEGORY_VALUE,
    SET_MARKET_NAME_VALUE,
    GET_MARKETS_BY_NAME,
    GET_MARKETS_BY_NAME_START,
    GET_MARKETS_BY_NAME_SUCCESS,
    GET_MARKETS_BY_NAME_FAIL,
    GET_MARKETS_BY_CATEGORY,
    GET_MARKETS_BY_CATEGORY_START,
    GET_MARKETS_BY_CATEGORY_SUCCESS,
    GET_MARKETS_BY_CATEGORY_FAIL,
    RESET_MARKETS,
    SET_LOCATION,
    SET_DISPLAY_LOCATION,
    GET_MARKETS_BY_NAME_AND_LOCATION,
    GET_MARKETS_BY_NAME_AND_LOCATION_START,
    GET_MARKETS_BY_NAME_AND_LOCATION_SUCCESS,
    GET_MARKETS_BY_NAME_AND_LOCATION_FAIL,
    GET_MARKETS_BY_CATEGORY_AND_LOCATION_START,
    GET_MARKETS_BY_CATEGORY_AND_LOCATION_SUCCESS,
    GET_MARKETS_BY_CATEGORY_AND_LOCATION_FAIL,
    GET_MARKETS_BY_CATEGORY_AND_LOCATION
}
